CREATE TABLE client (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(64) NOT NULL,
    prenom VARCHAR(64) NOT NULL,
    email VARCHAR(254) NOT NULL UNIQUE,
    ville VARCHAR(64) NOT NULL,
    date_inscription DATE NOT NULL
);

CREATE TABLE produit (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nom VARCHAR(128) NOT NULL,
    categorie VARCHAR(64) NOT NULL,
    prix NUMERIC(10, 2) NOT NULL CHECK (prix > 0),
    stock INTEGER NOT NULL CHECK (stock >= 0)
);

CREATE TABLE commande (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_id BIGINT NOT NULL REFERENCES client(id),
    date_commande DATE NOT NULL,
    statut VARCHAR(16) NOT NULL
        CHECK (statut IN ('payée', 'expédiée', 'livrée', 'annulée'))
);

CREATE TABLE ligne_commande (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    commande_id BIGINT NOT NULL REFERENCES commande(id),
    produit_id BIGINT NOT NULL REFERENCES produit(id),
    quantite INTEGER NOT NULL CHECK (quantite > 0),
    prix_unitaire NUMERIC(10, 2) NOT NULL CHECK (prix_unitaire > 0),
    UNIQUE (commande_id, produit_id)
);
